### ISSUE TITLE
Clarification on `rets.pkl` File in SAC Experiment Results  

### ISSUE THREAD

**Issue by amantuer** [sukritiverma1996/SARC#3]
Hi,  

Thank you again for your work on the SARC algorithm and for providing this excellent implementation. I previously posted a question about certain output files generated during SARC experiments, and I greatly appreciate the insights you’ve shared.  

I now have a follow-up question about the `rets.pkl` file located in the `sac_dmCheetahRun_400300_retroloss_2_s123` folder. Specifically:  

1. Where in the codebase is this file generated?  
2. What is the purpose of this file, and how does it contribute to the overall experiment or analysis (e.g., convergence tracking or other evaluations)?  

I’ve reviewed related files like `logx.py`, `sac.py`, and the evaluation notebooks, but I couldn’t pinpoint where this file is created or how it is used.  

Thank you in advance for your guidance, and I truly appreciate the time you take to support the community exploring retrospective learning.  

Best regards

**Comment by sukritiverma1996** [comment]
Hi,
It was probably for understanding purposes of average episodic returns obtained (with and without retro loss) during training and developing the method.
I'm happy to correspond on email if you're trying to dive deep into the method, I don't think opening issues on git is the best way for analysis related things if the code works. Please email for follow-up investigation/deep-dive.
